### ISSUE TITLE
Missing user guide

### ISSUE THREAD

**Issue by sumwar** [t-wolfeadam/AnyLogic-Pypeline#13]
Cannot locate full user guide. Can you please provide a path. Thanks

**Comment by t-wolfeadam** [comment]
Hi @sumwar, the user guide has been migrated into the wiki. Click on the Wiki tab above or here's a direct link: https://github.com/t-wolfeadam/AnyLogic-Pypeline/wiki
From there, you can navigate the pages on the right.
In retrospect I should've added a comment to the main readme about this; I'll do that now 😅

**Comment by sumwar** [comment]
@t-wolfeadam, thanks for posting that update. This is a great addition to AnyLogic.
