### ISSUE TITLE
fromJson for an int[][]

### ISSUE THREAD

**Issue by ChristianMalan** [t-wolfeadam/AnyLogic-Pypeline#15]
Hi, 

Thank you for the quick feedback last time, it really helped a lot. 

I am once again stuck.

I'm looking to convert the output from my python script `run_vehicle_routing_sweep` into an array of type *int[][]* in AnyLogic. In this case, the output from the python script is: 
>[
>[-1, 0, 6, 4, 1, -1], 
>[-1, 2, 3, 5, -1]
>]

I try to convert it into something useable in AnyLogic with the following code:

```
String sweep_result = pyCommunicator.runResults(String.class, String.format("run_vehicle_routing_sweep(%s,%s,%s)", customerJSON, vehicle_capacityJSON, depotJSON));

traceln("Sweep results: " + sweep_result);

int[][]route_order = pyCommunicator.fromJson(sweep_result, int[][].class);

traceln("Local route order: " + route_order[0]); 
```

This results in the output:

> Sweep results: [[-1, 0, 6, 4, 1, -1], [-1, 2, 3, 5, -1]]
> Local route order: [D@63d3832e

Do you have any suggestions?  
I also tried to use a dictionary approach, but that gives additional errors (relating to java expecting double quotes, rather than the single quotes from the python dictionary).

I don't know if my approach is off, or if it is a bug. Either way, I would really appreciate some help.

**Comment by t-wolfeadam** [comment]
@ChristianMalan , I'm closing this for now, but if you have any more questions about this, feel free to ask
