### ISSUE TITLE
Reinforcment Learning

### ISSUE THREAD

**Issue by doncha88** [t-wolfeadam/AnyLogic-Pypeline#18]
Hello, can you please tell me if you are planning to release a version with support for reinforcement learning? Thanks

**Comment by t-wolfeadam** [comment]
Hello! Pypeline will never have support for RL training (for a variety of reasons, discussed in the webinar Q&A). 

However, a library to allow for this is in the works! The plan is to release it before the end of Q3 this year - so 1 to 2 months 😃
