### ISSUE TITLE
Anaconda or pip environment support

### ISSUE THREAD

**Issue by HgmerFipsi** [t-wolfeadam/AnyLogic-Pypeline#3]
The current pypeline libary version allows me to select a python interpreter using a custom path. 
However, when using virtual environments it is required to activate the environment first.

Hence, I am wondering wether a workaround exists to activate python environments such as conda or pip before executing the modell in AnyLogic?
Thank you in advance !

**Comment by t-wolfeadam** [comment]
> Hence, I am wondering wether a workaround exists to activate python environments such as conda or pip before executing the modell in AnyLogic?

No workarounds needed - the latest version (1.4) should now utilize your conda/pipenv libraries automatically (when you point it to a relevant python executable)!
