### ISSUE TITLE
Issue with reflectiveObjects

### ISSUE THREAD

**Issue by lorenzo-ragazzini** [t-wolfeadam/AnyLogic-Pypeline#39]
Type sun.reflect.generics.reflectiveObjects.ParameterizedTypeImpl is not accessible.

Error directly visibile in Java code in some of the examples.
Using JRE 11, toJson return error related to ParameterizedTypeImpl.
Using JRE 10, a method for handling String is missing.

**Comment by t-wolfeadam** [comment]
Excuse my delay in seeing this -- I can't deduce where to start diagnosing without more info. Can you specify which examples you're trying to run or upload a model you're using that has this issue?

**Comment by t-wolfeadam** [comment]
Feel free to reopen if this is still a problem
