### ISSUE TITLE
Bug with Mac 

### ISSUE THREAD

**Issue by mgaury** [t-wolfeadam/AnyLogic-Pypeline#41]
Hello,

I have this error when I try to run Anylogic with pyCom :

Error during model startup:
root.pyCom:
Problem with setting up Python Subprocess
Caused by: Python process failed to properly start. This process needs to be started by a 'live' agent. Error message from process: 'Traceback (most recent call last):
  File "/var/folders/ln/hpcn96rx41j38zx70j7m_r0h0000gn/T/pypeline-server_9841271844594326379.py", line 5, in <module>
    from json.decoder import JSONDecodeError
ImportError: cannot import name JSONDecodeError

Can you help me ?

Thank you in advance,

Mickael

**Comment by t-wolfeadam** [comment]
It seems like you're trying to programmatically create the Python Communicator agent? If you can share your model, it would help in troubleshooting.

**Comment by mgaury** [comment]
Thank you for your quick reply.
The model I try to run is the Simple Hospital (AI Tested) from the exemples.

**Comment by mgaury** [comment]
When I try to use python3, I get this error : 
Error during model startup:
root.pyCom:
ModuleNotFoundError("No module named 'numpy'")java.lang.RuntimeException:

**Comment by t-wolfeadam** [comment]
Ah right, I see what the problem is now. Macs have Python 2 installed by default, so if you initialize the PyCommunicator with the default `python`, that's what it uses, and Pypeline does not support Python 2. 

Your update fixes to use Python 3 but as the error suggests, you're missing the numpy library, so you'll need to install that (and any other dependencies mentioned by the model). The simplest way that usually works is `python3 -m pip install <library>`

**Comment by mgaury** [comment]
Thank you for your reply.
The thing is I already installed this package
 (python3 -m pip install numpy
Requirement already satisfied: numpy in /Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages (1.19.5)).

This is why I don't understand. Does it need a special env to run ?

**Comment by t-wolfeadam** [comment]
> Requirement already satisfied: numpy in /Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages (1.19.5))

There might be a weird path issue happening related to you being on a Mac (I admittedly haven't extensively tested Pypeline on it). 

Try following the instructions listed on the [Wiki's Setup page](https://github.com/t-wolfeadam/AnyLogic-Pypeline/wiki/Setup) but configure it to use the "python3" command. Make sure the path it shows is similar to the mentioned one. If it's not, let me know what it is
