### ISSUE TITLE
Issue with AnyLogic 8.8.2

### ISSUE THREAD

**Issue by BenUhlig2** [t-wolfeadam/AnyLogic-Pypeline#42]
I'm getting the following error under AnyLogic 8.8.2:

> java.lang.ClassCastException: class [Com.anylogic.engine.presentation.ModelElement Descriptor Utils;
> cannot be cast to class [Lcom.anylogic.engine.presentation.ModelElementDescriptor; ([Lcom.anylogic.engine.presentation.ModelElementDescriptorUtils;
> and [Lcom.anylogic.engine.presentation.ModelElementDescriptor; are in unnamed module of loader 'app')

With AnyLogic 8.8.1 everything is working nicely. I'm suggesting not to (auto)update AnyLogic when using Pypeline.

By the way: thanks for this great library!

**Comment by t-wolfeadam** [comment]
Hi, glad to hear you've enjoyed it up to this point! And thanks for posting this -- fortunately the fix just required the library to be recompiled/reexported in the latest version (guessing they changed something internally). 

I went ahead and did that and published a new version: [download from Releases](https://github.com/t-wolfeadam/AnyLogic-Pypeline/releases/tag/v1.7.1).
