### ISSUE TITLE
jsonifier library error

### ISSUE THREAD

**Issue by frhann14** [t-wolfeadam/AnyLogic-Pypeline#51]
![py issue](https://github.com/t-wolfeadam/AnyLogic-Pypeline/assets/126521811/3b773094-02ee-4966-9700-dc6d04fce29d)

2 Errors after installing pyCommunicator in Anylogic 8.8.3

**Comment by t-wolfeadam** [comment]
Thank you both for reporting this -- looking into it now

**Comment by t-wolfeadam** [comment]
@frhann14 / @snake624 Now fixed in [v1.9.1](https://github.com/t-wolfeadam/AnyLogic-Pypeline/releases/tag/v1.9.1) 😃

**Comment by frhann14** [comment]
Thank you @t-wolfeadam .  Works like a charm now :)
