### ISSUE TITLE
Pypeline and AnyLogic Cloud 

### ISSUE THREAD

**Issue by andreaFrrr** [t-wolfeadam/AnyLogic-Pypeline#54]
Hi there! This is not really a problem, but rather a question. On the anylogic website it says that pypeline does not work with anylogic cloud. Are there any plans to integrate the library with the cloud? For example, I would personally find very useful to be able to export a model that uses python scripts to the cloud and then use the functionalities of the cloud API to run the model programmatically.

**Comment by t-wolfeadam** [comment]
Hi! For Public Cloud, this is not possible due to the fact that Pypeline relies on a Python on the system it's running on, which the Public Cloud does not (and likely will not) provide. However if you have access to a version of Private Cloud, and the admin of it is open to installing Python and the necessary modules for your scripts, then it's entirely possible (as is the case for our internal one, which you can see in the SS below):

![image](https://github.com/t-wolfeadam/AnyLogic-Pypeline/assets/40703071/ff7bb54b-320b-4c21-91b6-a88e1751a927)

**Comment by andreaFrrr** [comment]
Hi! Thank you very much for the answer. I asked you this question because I was thinking of buying a subscription to AL Cloud to do what I explained in the first comment. So if I start a model in my private AL Cloud and I have Python installed as I need it to develop the model with AL Desktop, can you assure me that it will work? In addition, what happens if the generation and building of a model is based on some Excel files that I have locally (on my PC) and that can be modified by a Py script? Will it still work?

**Comment by t-wolfeadam** [comment]
The Private Cloud is different a Public Cloud subscription (and much more expensive), as you're buying the software used to run the Cloud platform itself and hosting it on your own machine(s) -- this is what makes it possible to use Pypeline: you (or the admin) would be installing Python on the machine the Cloud is running on (specifically in the executor Docker container used to run the models) -- so assuming you have the access and permissions in place to do this, it would work. Again though, this will _not_ work for a Public Cloud subscription.

> what happens if the generation and building of a model is based on some Excel files that I have locally (on my PC) and that can be modified by a Py script?

The same thing if it's modified by Java and uploaded to the Cloud (any version/edition of it) -- you can specify input/output files in the model's Run Configuration page. After uploading you can override the input file and after running it you can download the output file (which could be the same file technically). You can [run a demo here](https://cloud.anylogic.com/model/efaa731e-8eb3-4479-9afc-79b1651115f6?mode=SETTINGS) and [download its source here](https://github.com/t-wolfeadam/AnyLogic-Pypeline/files/12187434/Excel.IO.Cloud.Demo.zip) (which includes the "clean" version of the input file).
