### ISSUE TITLE
Using toJson for a filtered subset of agent population  

### ISSUE THREAD

**Issue by ChristianMalan** [t-wolfeadam/AnyLogic-Pypeline#6]
Hi. 

I'm not sure if this is the appropriate place to post this. If it is not, please refer me to somewhere I can receive help with Pypeline functions.

Currently I can use _toJson_ to convert an agent population into a JSON string, which may then be used as input to a Python script.

The problem faced currently is that I would like to use only a **subset of the agent population as input**. I therefore filter the population, which gives a list of agents as output. When attempting to use _toJson_ with this list, I get the following error:

"_This agent is already defined as agent living in space 'Continuous' and can't have behaviour for space 'Discrete 2D'_"

My code is as follows: 

```
List routing_sub_population = filter(customers, c -> c.inState(Customer.statechart_state.awaiting_regular_delivery));
traceln("List: " + routing_sub_population);
String someListToJson =  pyCommunicator.toJson(routing_sub_population, true);
traceln("List: " + someListToJson);
```

**Comment by t-wolfeadam** [comment]
Hello! This is definitely the place the post questions/report issues.

I wasn't able to replicate your exact error regarding the space - that might be a separate issue. But I did notice that when you try to use `toJson` with a Java list containing Agent elements (e.g., what you get when you use `filter`), it does throw a "JsonMappingException" error. 

In short, this is a bug - one that I just fixed and pushed an update for. I will include it in the next release. I also pushed the updated jar; for now you can access it by clicking the "download" button on this page: https://github.com/t-wolfeadam/AnyLogic-Pypeline/blob/master/Export/Pypeline.jar

Just replace your current Pypeline.jar with the downloaded one, then either remove/add the lib back in via the "Manage libraries" wizard in the Palette or just restart AL. After that, you should be good to go!

I'm closing for now, feel free to comment back if you encounter any more related issues :)

**Comment by ChristianMalan** [comment]
Thank you so much for the response and the fix! It seems to be working fine now!

I'm embarking on quite a large project, so might be back with more questions at some stage.

Regards :)
