### ISSUE TITLE
Python and Anylogic Connection

### ISSUE THREAD

**Issue by selinozen** [t-wolfeadam/AnyLogic-Pypeline#71]
Hello dear t-wolfeadam,

I am trying to connect Anylogic and Python. I know there is a Pipeline tool in Anylogic but I intend to get the non-stop generated output to Anylogic block in real time. I have searched for it and I encountered Python's socket library and Anylogic's REST API. I am confused about which one to use. By the way, I want to get the data from an IoT device as an input to Python.

**Comment by t-wolfeadam** [comment]
Hi, so the Pypeline tool is this one :)

I'm not sure what you mean by "real-time" - simulation tools like AnyLogic are intended to run *faster* than real time, so typically any external endpoints are queried at the start of run to initialize the model and then it's executed under its own rules. 

Also, Pypeline is probably exactly what you want. It uses Python's socket library for communication. For reference, AnyLogic's REST API is specifically for running models uploaded to the AnyLogic Cloud, so it's not what you want.

I made a very simple example model showing how it works, similar to the problem you described (though the provided examples are typically more useful). Please read the documentation if you need help installing it or for more information.

[Model344.zip](https://github.com/t-wolfeadam/AnyLogic-Pypeline/files/14223694/Model344.zip)
