### ISSUE TITLE
example model can not be opened

### ISSUE THREAD

**Issue by yuriypodvalny** [t-wolfeadam/AnyLogic-Pypeline#73]
im also having this issue. How was it solved?

_Originally posted by @yuriypodvalny in https://github.com/t-wolfeadam/AnyLogic-Pypeline/issues/40#issuecomment-2112595172_

**Comment by t-wolfeadam** [comment]
Can you share which example model youre trying to open? Share the sources for the example model if you can. Also please share the specific error message you're getting (a screenshot would be great)

**Comment by yuriypodvalny** [comment]
i cant reproduce it. I suspect i was trying to open the model before unzipping it. So you can close this issue.
